### ISSUE TITLE
I’m going to refund this app. Sad. 

### ISSUE THREAD

**Issue by anon238** [smmr-software/privacy-redirect-safari#12]
I was looking for exactly something like this but probably developers doesn’t quite understand the underlying technology of Safari. This app is anything but privacy friendly. It loads the website and then redirects you to is which still sends your data to the server.

**Comment by anon238** [comment]
I’m gonna wait couple days if development tries to fix this before refunding because I really needed something like this. But fix the privacy issues please b

**Comment by FIGBERT** [comment]
Hey there! We understand the underlying technology of Safari, and have to work within its limitations. The redirect occurs as soon as possible, but due to limitations in the API support of Safari we cannot redirect before the initial request is sent. Please see [previous](https://github.com/smmr-software/privacy-redirect-safari/issues/5#issuecomment-920191444) [discussions](https://github.com/smmr-software/privacy-redirect-safari/issues/10#issuecomment-963470001) on the topic.

**Comment by anon238** [comment]
That’s totally not true. But that’s why I’m refunding. It’s false privacy.

**Comment by FIGBERT** [comment]
酷
