### ISSUE TITLE
Does not redirect

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [smmr-software/privacy-redirect-safari#23]
It worked the first few days.
Now it just does not redirect at all.
Is there a way to send logs or does it log at all?

**Comment by FIGBERT** [comment]
It doesn't really log, but I'd be happy to help you troubleshoot. First, a few questions:
1. What platform are you on? Are you up to date?
2. Do you have all redirects enabled?
3. Have you given Privacy Redirect permission to run on all the sites it asks for in Safari?

**Comment by Unkn0wn-MDCLXIV** [comment]
Im on an iPhone 12 Pro running iOS 15.2.1. The app is up to date.
I have all redirects enabled.
Can’t remember if it asked for permission, not sure where to check its permission.

**Comment by FIGBERT** [comment]
The permissions is a common problem – Apple does *not* make it obvious *at all*. Check out the docs [here](https://developer.apple.com/documentation/safariservices/safari_web_extensions/managing_safari_web_extension_permissions#3599257) to see if that's the issue.

**Comment by Unkn0wn-MDCLXIV** [comment]
Looks like that’s the issue.
Is there a way to allow all at once or allow the extension to run on all sites?
Then you might be able to redirect or change the url before accessing the unwanted websites.

**Comment by FIGBERT** [comment]
> Is there a way to allow all at once or allow the extension to run on all sites?

We can request permission for Privacy Redirect to run on all sites, but we avoid this purposefully so that we're only active where we need to be.

Allowing all the sites we request at once should be one of the options that pops up when you're approving permissions for the first time.

> Then you might be able to redirect or change the url before accessing the unwanted websites.

This is a separate problem, which we've [addressed in the past](https://github.com/smmr-software/privacy-redirect-safari/issues/10#issuecomment-1001232820). Unfortunately, this is a limitation in Safari which we cannot work around just yet.

> Looks like that’s the issue.

Glad I could help!
