### ISSUE TITLE
Privacy implications of “Enable on all websites”?

### ISSUE THREAD

**Issue by garth-xmr** [smmr-software/privacy-redirect-safari#25]
iOS is asking me if I want to enable this extension on all websites, and says the app developer can see what sites I’m visiting. Is this true?

**Comment by FIGBERT** [comment]
We do not access all websites, but instead request only those that we need (an unfortunately very long list due to Google's bajillion TLDs). You can see a list of all sites we request access to [in our `manifest.json`](https://github.com/smmr-software/privacy-redirect-safari/blob/main/iOS%20(Extension)/Resources/manifest.json#L15-L1367).

The extension can indeed access these sites when you visit them – that's how we redirect them – but the app never establishes a network connection and all processing is done locally. In fact, we don't even have any servers we could send your data to!
