### ISSUE TITLE
Fork from Libredirect instead of Privacy Redict

### ISSUE THREAD

**Issue by sith-on-mars** [smmr-software/privacy-redirect-safari#34]
The development of Privacy Redirect has stopped for several months. There is a fork of Privacy Redirect called [Libredirect](https://github.com/libredirect/libredirect), which receives frequent updates and the developer is quite responsive. It has more redirect function and instances. Would you consider to switch to Libredirect as the base?

**Comment by FIGBERT** [comment]
Our extension has progressed significantly since we initially forked Privacy Redirect – we no longer use any original code, and our extension functions using different mechanisms due to API differences between Chrome/Firefox and Safari.

We commend the development of Libredirect, and have had our eyes on it for a bit. We've adopted new frontends such as [rimgo](https://codeberg.org/video-prize-ranch/rimgo), like Libredirect, and will continue to do so. There are some redirects that Libredirect implements that we believe unnecessary and thus have not implemented.

Updating the list of instances is probably something we should do in the near future.

I hope this clarifies things. tldr: our changes to the original Privacy Redirect are extensive, and we don't operate using it as a "base," and thus cannot switch to Libredirect "as the base."

**Comment by sith-on-mars** [comment]
That clear things up! Thank you!
