### ISSUE TITLE
Direct access to options from Safari 

### ISSUE THREAD

**Issue by lothar-cell** [smmr-software/privacy-redirect-safari#37]
It would be great if clicking on the extension icon in Safari would bring up the options rather than a window to "Open App", which then opens an additional window with the options.

<img width="628" alt="Screenshot 2022-05-19 at 16 17 49" src="https://user-images.githubusercontent.com/2356354/169315896-4c591130-a1c9-44e4-a0ae-5ff8e3cf9404.png">

**Comment by FIGBERT** [comment]
We made the conscious decision to have users customize settings via the app, as we think it's more ergonomic and Mac-like. Web extensions in Chrome are configured with HTML menus and popovers. Privacy Redirect for Safari is a macOS app, and it is configured natively. It's a tradeoff, but one we think is work it.

**Comment by lothar-cell** [comment]
Adding an extra step to the UI without actual function, is definitely a strange interpretation of Apple's UI design philosophy, if you don't mind me saying, but your choice is yours. I just wish there was an alternative when it comes to Safari.

**Comment by FIGBERT** [comment]
Ideally we would open the app when you click the icon in Safari, as in [Vimari](https://televator.net/vimari/), but last we looked the API was not available to us based on the way we built the app. I will open an issue in our tracker and we can look into this again.

**Comment by lothar-cell** [comment]
I'd like to leave this here as an inspiration, I think Adguard has done a great job in this regard:

<img width="313" alt="Screenshot 2022-06-01 at 6 31 50" src="https://user-images.githubusercontent.com/2356354/171328113-c9f32cef-7aa8-4a43-8986-28c73e43af4f.png">

**Comment by FIGBERT** [comment]
After further investigation, it looks like [opening the Swift app on click](https://developer.apple.com/documentation/safariservices/sfsafariextensionhandling/1639511-toolbaritemclicked) is limited to Safari App Extensions. Vimari [does this](https://github.com/televator-apps/vimari/blob/0d31b6af58f8779fb1896d566f11d8ed586e5fb8/Vimari%20Extension/SafariExtensionHandler.swift#L69-L73). Unfortunately, this isn't yet supported for Safari Web Extensions – I'm going to close this issue here for now, and move the internal version to our backlog.

We'll keep an eye out for changes in this area, because we'd love to support this eventually.
