### ISSUE TITLE
Improvements to redirection

### ISSUE THREAD

**Issue by httpjamesm** [smmr-software/privacy-redirect-safari#45]
Currently, Privacy Redirect waits for the target page to load (like Reddit), and then redirects the user to the selected private instance. However, I noticed that the [Kagi Search extension](https://github.com/kagisearch/Kagi-Search-for-Safari-macOS) is able to redirect users to their search engine without needing to wait for the default search engine to load.

I wonder if it's possible to implement the same redirection code that Kagi uses into this extension for a faster and more private experience?

**Comment by FIGBERT** [comment]
Kagi is a [Safari App Extension](https://developer.apple.com/documentation/safariservices/safari_app_extensions), Privacy Redirect for Safari is a [Safari Web Extension](https://developer.apple.com/documentation/safariservices/safari_web_extensions). Unfortunately, the API differences mean that our current strategy is the best way we can redirect at the moment.

It may be worth considering a migration to the other API. It's unfortunate, because Web Extensions are actually the newer API.
